dist: trusty
sudo: required

language: c
compiler:
    - gcc
    - clang

addons:
    apt:
        packages:
            - autoconf
            - automake
            - make
            - xsltproc
            - docbook-xsl
            - docbook-xml
            #- uuid-dev
            - libglib2.0-dev
            - libsoup2.4-dev
            #- libavahi-glib-dev
            - libgssdp-1.0-dev
            - libcairo2-dev
            - libpango1.0-dev
            - libgdk-pixbuf2.0-dev
            - libxcb1-dev
            - libxcb-util0-dev
            - libxcb-randr0-dev
            - libxcb-shape0-dev
            - libxcb-ewmh-dev
            - libpurple-dev
            #- libpulse-dev
            - libsndfile1-dev
            - libspeechd-dev
            - libcanberra-dev
            # For libnkutils tests
            - gnome-icon-theme-extras
            - gnome-icon-theme-symbolic
            - sound-theme-freedesktop
            - pidgin-data
install:
    - sudo apt-get install -y uuid-dev libavahi-glib-dev libpulse-dev

before_script:
    - autoreconf -fiv
    - ./configure --disable-silent-rules --disable-ipv6 --disable-nd-wayland --enable-nd-fbdev --enable-tts --enable-canberra --enable-im --with-dbussessionservicedir=/usr/share/dbus-1/services
script:
    - make -j2
    - make -j2 check
    - make -j2 distcheck DISTCHECK_CONFIGURE_FLAGS="--disable-ipv6 --disable-nd-wayland --enable-nd-fbdev --enable-tts --enable-canberra --enable-im"
after_failure:
    - cat test-suite.log
    - cat eventd-*/test-suite.log


notifications:
    email: false
